### PR TITLE
Add muti-module test

### PR DESCRIPTION
**Pull request by mezarin**
This PR adds a test that uses the OL maven plugin muti-module support.
It downloads/uses the [OL guide multimodule application application](https://github.com/openliberty/guide-maven-multimodules.git). Note that odo currently does not make use of projects defined in the devfile.

### CODE REVIEW

**Review by scottkurz — COMMENTED** [review]
LGTM, thx for doing all the bash array changes.

I do wonder though about the need to change the devfile to add a test-compile.

Let's talk about that more.

**Comment by mezarin** [comment]
Per a conversation with Scott. The test command will be updated to include compiler:compile.
While i am changing that, i am also updating The OL version level being used to 21.0.0.9 and the devfile schema version to 2.1.0.

**Review by scottkurz — COMMENTED** [review]
Hmm..this could be done without updating the stack image.   

What's your thinking behind bumping up the minor version: 0.6->0.7, 0.1->0.2?   

I'm guessing you're just thinking "while we're updating the schema version, we might as well make this a more substantial update and go to 21009" rather than carefully thinking through the different back compat paths.    E.g. is it possible for a child 2.0.0 to have a 2.1.0 parent?

Not sure... maybe this is early enough that we don't really care but it'd be nice to do a quick investigation and try a 2.0.0 child w/ 2.1.0 parent and see what happens.

**Review by scottkurz — APPROVED** [review]

**Comment by mezarin** [comment]
Just to recap out conversation. The devfile schema version change was mainly the reason for the minor version change since the stack provides/releases the devfile. Backward compatibility is implied by the semver versioning scheme. Preliminary tests using a parent devfile at the 2.0.0 level with a child at the 2.1.0 using variables did not show any problems. Therefore the change.

**Pull request merged**
