### PR TITLE
Remove odo test from git actions

### PR DESCRIPTION
**Pull request by awisniew90**
Signed-off-by: Adam Wisniewski <awisniew@us.ibm.com>

### CODE REVIEW

**Review by scottkurz — COMMENTED** [review]
Maybe we could just throw in an `odo log`  since we lost the original `odo log` output after piping it into the grep?

**Comment by awisniew90** [comment]
@scottkurz  - I think that's what odo test --show-log should be doing.

**Comment by scottkurz** [comment]
> @scottkurz - I think that's what odo test --show-log should be doing.

I didn't think it showed the whole log including initial pod startup but just the log once the `odo test` was issued.  Just thinking in case the earlier log was  useful?

**Review by scottkurz — APPROVED** [review]
Made comment but will approve in case you want to merge.

**Pull request merged**
