### PR TITLE
Fix outer loop permission issues

### LINKED ISSUE #81: 0.2.4 Dockerfile failing in pipeline build with permission denied
Log from pipeline when doing docker build:
```
step-build
STEP 1: FROM openliberty/application-stack:0.2 AS compile
Getting image source signatures
Copying blob sha256:ffc6e0e42cd81d0e1330e0d62c9c327cbe502fbbd75f1cc2096b51cba31b77fa
Copying blob sha256:ec1681b6a383e4ecedbeddd5abc596f3de835aed6db39a735f62395c8edbff30
Copying blob sha256:c4d668e229cd131e0a8e4f8218dca628d9cf9697572875e355fe4b247b6aa9f0
Copying blob sha256:62ce84dcd6db67c652f91b733dbf24a48eed62735866a801c98bcc6f463c9827
Copying blob sha256:07d56f29999d747adefdac6ab4cb22a82495aacf233fc1d8947aef4f088d381c
Copying blob sha256:5136161c2195466b3ad1191bc1212d3c57d52a27da5b804c4b7e56928ef9f42c
Copying blob sha256:e636531b9fc9d9152735e0598096be65eac77eb43eac010b5d394267ef3b0b69
Copying blob sha256:c7395efd8cd62a39cd6b388309ef90a413de5fdbdf822e2b384e8d6b0c3a4cb1
Copying blob sha256:d4b5e2a72a9ce660270ca823173eb40f0b54bfc8e6dfa68d71a2fd4a4faafddf
Copying blob sha256:5313e5eb605f5a04c7837a7505dfa4175a06cd332b48b62c529dd720d652daec
Copying blob sha256:1db0db446e350d6b7ce76724cd7f469447060deb095c8e8a57518163b0f37b6e
Copying blob sha256:4df258a59cc9390baca73bb77e53c97f42040fb26d6535f7cedee471bc28b30b
Copying blob sha256:5b20fc98b693edb787ab0361cb8e3e258147eca36402f36d164991703b920e74
Copying blob sha256:21b550370a2317e29b0bff83150cbb1be5dcfe2510fb104c7b49eb25f2657232
Copying blob sha256:b8fabb2a82151bfa81ea8f8c7c0ed9cefa32572ab656da1f1fe6c46062a30e16
Copying config sha256:52594e517d37fe606642ac5cc352f19f81cbc43ece339af40bd355e5985dc0e0
Writing manifest to image destination
Storing signatures
STEP 2: RUN mkdir /configlibdir && mkdir /config && mkdir /shared
mkdir: cannot create directory ‘/configlibdir’: Permission denied
error building at STEP "RUN mkdir /configlibdir && mkdir /config && mkdir /shared": error while running runtime: exit status 1
```

Also from manual test:
```
$ docker run -ti openliberty/application-stack:0.2 /bin/sh
Unable to find image 'openliberty/application-stack:0.2' locally
0.2: Pulling from openliberty/application-stack
ec1681b6a383: Already exists
c4d668e229cd: Already exists
07d56f29999d: Pull complete
5136161c2195: Pull complete
ffc6e0e42cd8: Pull complete
62ce84dcd6db: Pull complete
c7395efd8cd6: Pull complete
e636531b9fc9: Pull complete
d4b5e2a72a9c: Pull complete
5313e5eb605f: Pull complete
1db0db446e35: Pull complete
4df258a59cc9: Pull complete
5b20fc98b693: Pull complete
21b550370a23: Pull complete
b8fabb2a8215: Pull complete
Digest: sha256:be82e25642f83649ef8223508fa5298fa3ebe40bd3ebaaa76328cffce2a52705
Status: Downloaded newer image for openliberty/application-stack:0.2
sh-4.4$ whoami
java_user
sh-4.4$ mkdir /configlibdir
mkdir: cannot create directory ‘/configlibdir’: Permission denied
sh-4.4$ mkdir /config
mkdir: cannot create directory ‘/config’: Permission denied
sh-4.4$ mkdir /shared
mkdir: cannot create directory ‘/shared’: Permission denied
sh-4.4$ exit
```

### PR DESCRIPTION
**Pull request by scottkurz**
Signed-off-by: Scott Kurz <skurz@us.ibm.com>

Fixes #81

### CODE REVIEW

**Review by ajm01 — APPROVED** [review]
LGTM

**Comment by scottkurz** [comment]
Closing as superseded by #83

**Comment by scottkurz** [comment]
Going to use this to just ship the stack image Dockerfile change, so we can proceed to build it.

**Review by ajm01 — APPROVED** [review]
LGTM

**Pull request merged**
